"""
Django settings for vgw4 project.

Generated by 'django-admin startproject' using Django 3.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import sys
import json
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']

from sys import platform
import socket

HOSTNAME = socket.gethostname()
print('platform', type(platform), platform)
if HOSTNAME == 'VN-JeongJaeheon':
    with open('C:\\workspace\\etc\\config.json') as config_file:
        config = json.load(config_file)
    SECRET_KEY = 'w)s(m6zfj1hbf)z&&^-_33u^y+*%9)k-j^oy9cks3hhy*$i!mu'
    ENGINE = 'django.db.backends.postgresql'
    NAME = 'sample_vgw'
    USER = 'postgres'
    PASSWORD = config["PASSWORD"]
    HOST = 'localhost'
    PORT= '5432'
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, 'static'),
    ]
    DEBUG = True
elif HOSTNAME == 'VN-MunCheolHyun':
    with open('C:\\workspace\\etc\\config.json') as config_file:
        config = json.load(config_file)
    SECRET_KEY = 'w)s(m6zfj1hbf)z&&^-_33u^y+*%9)k-j^oy9cks3hhy*$i!mu'
    ENGINE = 'django.db.backends.postgresql'
    NAME = 'sample_vgw'
    USER = 'postgres'
    PASSWORD = '1234'
    HOST = 'localhost'
    PORT= '5432'
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, 'static'),
    ]
    DEBUG = True
else:
    SECRET_KEY = 'w)s(m6zfj1hbf)z&&^-_33u^y+*%9)k-j^oy9cks3hhy*$i!mu'
    ENGINE = 'django.db.backends.postgresql'
    NAME = 'sample_vgw'
    USER = 'postgres'
    PASSWORD = '1234'
    HOST = 'localhost'
    PORT= '5432'
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, 'static'),
    ]
    DEBUG = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'utilities',
    'member',
    'security',
    'home',
    # 'inquiry',

    # # 3rd Party Apps
    'bootstrapform',
    # # 'corsheaders',
    'crispy_forms',
    'django_celery_results',
    'django_celery_beat',
    'import_export',
    'rdkit',
    'rest_framework',
    'django_quill',
    'mathfilters',
    'matplotlib',
    # 'bootstrap4',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'vgw4.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates',)
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vgw4.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': BASE_DIR / 'db.sqlite3',
        'ENGINE': ENGINE,
        'NAME': NAME,
        'USER': USER,
        'PASSWORD': PASSWORD,
        'HOST': HOST,
        'PORT': PORT
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

os.environ["DJANGO_ALLOW_ASYNC_UNSAFE"] = 'true'

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Seoul'


USE_I18N = True

USE_L10N = True

# USE_TZ = True
USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


LOGIN_REDIRECT_URL = 'home'
LOGIN_URL = 'member-login'
